import PageLayouts from 'layouts/PageLayouts'
import Head from 'next/head'
import React, { SyntheticEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import axios from 'axios'
import Profile from 'pages/profile'

const Login = () => {
    const [success, setSuccess] = useState("")
    const [error, setError] = useState("")

    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [empty, setEmpty] = useState("")

    const router = useRouter()

    useEffect(() => {
        if (window.localStorage.getItem("refreshtoken")) {
            router.push("/profile")
        }
    }, [])

    const PostAPILogin = async (event: SyntheticEvent) => {
        event.preventDefault()

        if (email === "") {
            setEmpty("Email field must be filled")
        } else {
            setEmpty("")
        }

        const users = {
            email, password
        }

        try {
            const userResponse = await axios.post("http://localhost:8888/v1/login", users)
            router.push("/profile")
        } catch (error: any) {
            setError(error.response.data.message)
        }
    }

    const FailedAlert = ({ status }: any) => {
        return (
            <div className="alert alert-error shadow-lg p-4 rounded-lg my-4">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    <span className='text-xs'>{status}</span>
                </div>
            </div>
        )
    }

    return (
        <React.Fragment>
            <Head>
                <title>Frontend User Service</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <PageLayouts>
                <div className="w-full mt-3">
                    <form onSubmit={PostAPILogin} className="w-[90%] md:w-[500px] shadow-2xl bg-base-100 mx-auto p-8 border border-gray-600 rounded-xl" action="">
                        <h3 className="font-bold text-xl text-center mr-2">Login Account</h3>
                        <h3 className="font-normal text-sm mr-2 mt-2">Lets login to your account first</h3>
                        <div className="form-control mt-3">
                            {error}
                            {empty}
                            <label className="label">
                                <span className="label-text font-semibold">Email Address</span>
                            </label>
                            <input type="text" value={email} onChange={event => setEmail(event.target.value)} placeholder="Enter your email" className="input input-bordered" />
                        </div>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text font-semibold">Password</span>
                            </label>
                            <input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" className="input input-bordered" />
                            <label className="label">
                                <a href="/forgot-password" className="label-text-alt link link-hover">Forgot password?</a>
                            </label>
                        </div>
                        <div className="form-control mt-6">
                            <button className="btn btn-primary capitalize">Login Now</button>
                            <button className="mt-6 btn btn-ghost capitalize">Register</button>
                        </div>
                    </form>
                </div>
            </PageLayouts >
        </React.Fragment>
    )
}

export default Login