import axios from 'axios'
import PageLayouts from 'layouts/PageLayouts'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { SyntheticEvent, useState } from 'react'

const Register = () => {
    const [success, setSuccess] = useState("")
    const [error, setError] = useState("")

    const [email, setEmail] = useState("")
    const [phone, setPhone] = useState("")
    const [username, setUsername] = useState("")
    const [password, setPassword] = useState("")
    const [confirmPassword, setConfirmPassword] = useState("")

    const router = useRouter()

    const PostAPIRegister = async (event: SyntheticEvent) => {
        event.preventDefault()

        const users = {
            username, email, phone, password, confirmPassword
        }

        try {
            await axios.post("http://localhost:8888/v1/users", users)
            router.push("/auth/login")
        } catch (error: any) {
            if (error.response) {
                setError(error.response.data.message)
            }
        }
    }

    return (
        <React.Fragment>
            <Head>
                <title>Frontend User Service</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <PageLayouts>
                <div className="w-full mt-3">
                    <form onSubmit={PostAPIRegister} className="w-[90%] md:w-[500px] shadow-2xl bg-base-100 mx-auto p-8 border border-gray-600 rounded-xl" action="">
                        <h3 className="font-bold text-xl text-center mr-2">Registration</h3>
                        <h3 className="font-normal text-sm mr-2 mt-2">Lets register first to get trial premium features</h3>
                        <div className="form-control mt-5">
                            <label className="label">
                                <span className="label-text font-semibold">Username</span>
                            </label>
                            <input type="text" value={username} onChange={event => setUsername(event.target.value)} placeholder="Enter Username" className="input input-bordered" />
                        </div>
                        <div className="form-control mt-5">
                            <label className="label">
                                <span className="label-text font-semibold">Phone Number</span>
                            </label>
                            <input type="text" value={phone} onChange={event => setPhone(event.target.value)} placeholder="Enter Phone Number" className="input input-bordered" />
                        </div>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text font-semibold">Email Address</span>
                            </label>
                            <input type="text" value={email} onChange={event => setEmail(event.target.value)} placeholder="Enter your email" className="input input-bordered" />
                        </div>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text font-semibold">Password</span>
                            </label>
                            <input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" className="input input-bordered" />
                            <label className="label">
                                <a href="/forgot-password" className="label-text-alt link link-hover">Forgot password?</a>
                            </label>
                        </div>
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text font-semibold">Confirm Password</span>
                            </label>
                            <input type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} placeholder="Enter your password" className="input input-bordered" />
                            <label className="label">
                                <a href="/forgot-password" className="label-text-alt link link-hover">Forgot password?</a>
                            </label>
                        </div>
                        <div className="form-control mt-6">
                            <button className="btn btn-primary capitalize">Register Now</button>
                            <label className="label mt-3">
                                <p className="text-xs">Already have an account ?</p>
                            </label>
                            <button className="btn btn-ghost capitalize">Login</button>
                        </div>
                    </form>
                </div>
            </PageLayouts >
        </React.Fragment>
    )
}

export default Register