import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import PageLayouts from "layouts/PageLayouts"
import { SyntheticEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const [success, setSuccess] = useState(false)
  const [value, setValue] = useState(0)

  const router = useRouter()

  useEffect(() => {
    setInterval(() => {
      setValue((prev) => prev + 1)
    }, 400)

    if (value == 100) {
      router.push("/auth/login")
    }
  }, [value])

  const SuccessRegister = (event: SyntheticEvent) => {
    event.preventDefault()
    setTimeout(() => {
      setSuccess(true)
    }, 4000)
  }

  const SuccessAlert = () => {
    return (
      <div className="alert alert-success shadow-lg p-4 rounded-lg my-4">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span className='text-xs'>Yeaey, You are Successfully Register!</span>
        </div>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Frontend User Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayouts>
        <div className="w-full mt-24 text-center">
          <span className="font-semibold text-sm">Welcome to </span>
          <h1 className='font-bold text-5xl mt-3'>Frontend Playground</h1>

          <h1 className='font-normal text-md mt-8'>Wait.. will be redirected to login page automatically</h1>

          <div className="mt-3">
            <progress className="progress progress-warning w-80" value={value} max="100"></progress>
          </div>
        </div>
      </PageLayouts >
    </div >
  )
}

export default Home
